(load-file "~/.emacs.d/ample-emacs/core.el")
(ample-emacs/load-config-file "config-system")
(ample-emacs/load-config-file "config-packages")
(ample-emacs/load-config-file "config-interface")
(ample-emacs/load-config-file "config-misc")
(ample-emacs/load-config-file "config-key-bindings")
(ample-emacs/print-startup-message)
