(load-file "~/.emacs.d/ample-emacs/core.el")
(ae/load-file "config-system")
(ae/load-file "config-packages")
(ae/load-file "config-interface")
(ae/load-file "config-misc")
(ae/load-file "config-key-bindings")
(ae/print-startup-message)
